version: '2'

services:
  # Coldfusion container
  coldfusion2023:
    image: adobecoldfusion/coldfusion2023:latest
    ports:
      - 8500:8500
    environment:
      - acceptEULA=YES
      - password=admin
    volumes:
      - ./html:/app
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - "3001:80"
volumes:
  db-data: